repos:
  - repo: https://github.com/psf/black-pre-commit-mirror
    rev: 25.1.0  # Use the desired Black version (consider updating this)
    hooks:
      - id: black
        # Uses system default Python (works with Python 3.8+)
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
